### ISSUE TITLE
Wireless Model D-

### ISSUE THREAD

**Issue by oemsysadm** [korkje/mow#6]
I purchased a Wireless Model D-, before the purchase I asked Glorious if it had the same internals as the model O Wireless, and pointed them to your GitHub repo. They said it would likely work with your utility, but of course gave me a bunch of boilerplate about how they don't support it. I took the chance and bought one, however it obviously has a different USB ID than the MOW, and as such running mow just says it can't find a supported device:

```
./mow report battery
Error: No matching device found!
```

How do I go about adding the wired/wireless ID's to your code in order to try and get it recognized? I'm not a developer, and I have zero Rust experience, but I'd be willing to take a crack at it if it's just a matter of changing the ID in the code. It would be nice if there was a command line option to explicitly specify the ID, for testing with other models from the same vendor, or a config file where you can list the IDs you'd like it to recognize.

Below is the dmesg output when plugging this mouse in.

Wired:

```
[Sun May 22 12:52:49 2022] usb 3-1.2.4: Manufacturer: Glorious
[Sun May 22 12:52:49 2022] input: Glorious Model D- Wireless as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.0/0003:258A:2014.001F/input/input50
[Sun May 22 12:52:49 2022] hid-generic 0003:258A:2014.001F: input,hidraw17: USB HID v1.11 Mouse [Glorious Model D- Wireless] on usb-0000:03:00.0-1.2.4/input0
[Sun May 22 12:52:49 2022] input: Glorious Model D- Wireless Consumer Control as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2014.0020/input/input51
[Sun May 22 12:52:49 2022] input: Glorious Model D- Wireless System Control as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2014.0020/input/input52
[Sun May 22 12:52:49 2022] input: Glorious Model D- Wireless Keyboard as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2014.0020/input/input53
[Sun May 22 12:52:49 2022] input: Glorious Model D- Wireless as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2014.0020/input/input54
[Sun May 22 12:52:49 2022] input: Glorious Model D- Wireless as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2014.0020/input/input55
[Sun May 22 12:52:49 2022] hid-generic 0003:258A:2014.0020: input,hiddev96,hidraw18: USB HID v1.11 Keyboard [Glorious Model D- Wireless] on usb-0000:03:00.0-1.2.4/input1
[Sun May 22 12:52:49 2022] hid-generic 0003:258A:2014.0021: hiddev104,hidraw19: USB HID v1.11 Device [Glorious Model D- Wireless] on usb-0000:03:00.0-1.2.4/input2
```

Wireless:

```
[Sun May 22 12:53:01 2022] usb 3-1.2.4: Manufacturer: Glorious
[Sun May 22 12:53:01 2022] input: Glorious Model D- Wireless as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.0/0003:258A:2025.0022/input/input56
[Sun May 22 12:53:01 2022] hid-generic 0003:258A:2025.0022: input,hidraw17: USB HID v1.11 Mouse [Glorious Model D- Wireless] on usb-0000:03:00.0-1.2.4/input0
[Sun May 22 12:53:01 2022] input: Glorious Model D- Wireless Consumer Control as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2025.0023/input/input57
[Sun May 22 12:53:02 2022] input: Glorious Model D- Wireless System Control as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2025.0023/input/input58
[Sun May 22 12:53:02 2022] input: Glorious Model D- Wireless Keyboard as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2025.0023/input/input59
[Sun May 22 12:53:02 2022] input: Glorious Model D- Wireless as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2025.0023/input/input60
[Sun May 22 12:53:02 2022] input: Glorious Model D- Wireless as /devices/pci0000:00/0000:00:01.1/0000:01:00.2/0000:02:00.0/0000:03:00.0/usb3/3-1/3-1.2/3-1.2.4/3-1.2.4:1.1/0003:258A:2025.0023/input/input61
[Sun May 22 12:53:02 2022] hid-generic 0003:258A:2025.0023: input,hiddev96,hidraw18: USB HID v1.11 Keyboard [Glorious Model D- Wireless] on usb-0000:03:00.0-1.2.4/input1
[Sun May 22 12:53:02 2022] hid-generic 0003:258A:2025.0024: hiddev104,hidraw19: USB HID v1.11 Device [Glorious Model D- Wireless] on usb-0000:03:00.0-1.2.4/input2
```

**Comment by oemsysadm** [comment]
When replacing with the IDs 0x2014 and 0x2025 in main.rs on line 31 and 48, it builds, but running the tool, I get the following errors (I tried multiple reports and config settings and got the same error):

```
~/S/N/D/m/t/release (master) [2]> ./mow config scroll invert
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HidApiError { message: "hid_error is not implemented yet" }', src/main.rs:51:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

~/S/N/D/m/t/release (master) [101]> RUST_BACKTRACE=1 ./mow config scroll invert
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HidApiError { message: "hid_error is not implemented yet" }', src/main.rs:51:52
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.60.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1.60.0/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/1.60.0/library/core/src/result.rs:1749:5
   3: mow::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

~/S/N/D/m/t/release (master) [101]> RUST_BACKTRACE=full ./mow config scroll invert
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HidApiError { message: "hid_error is not implemented yet" }', src/main.rs:51:52
stack backtrace:
   0:     0x55cec60d22bc - std::backtrace_rs::backtrace::libunwind::trace::h4c82c30effa1ec8b
                               at /rustc/1.60.0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55cec60d22bc - std::backtrace_rs::backtrace::trace_unsynchronized::h04f51b94feda398c
                               at /rustc/1.60.0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cec60d22bc - std::sys_common::backtrace::_print_fmt::h83c260b7e0b0e807
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55cec60d22bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4c69548d53cef23e
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55cec60f070c - core::fmt::write::he1f7c3e09b6d48b1
                               at /rustc/1.60.0/library/core/src/fmt/mod.rs:1190:17
   5:     0x55cec60cee31 - std::io::Write::write_fmt::h7f5865fb08a452b9
                               at /rustc/1.60.0/library/std/src/io/mod.rs:1657:15
   6:     0x55cec60d4325 - std::sys_common::backtrace::_print::hd7f28ad4b7c7f649
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55cec60d4325 - std::sys_common::backtrace::print::hda6514e610876808
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55cec60d4325 - std::panicking::default_hook::{{closure}}::hec9b2f020ff35128
                               at /rustc/1.60.0/library/std/src/panicking.rs:295:22
   9:     0x55cec60d3fe4 - std::panicking::default_hook::hd76a5748cebf86d7
                               at /rustc/1.60.0/library/std/src/panicking.rs:314:9
  10:     0x55cec60d4a58 - std::panicking::rust_panic_with_hook::h372a0c94f5d85a2f
                               at /rustc/1.60.0/library/std/src/panicking.rs:698:17
  11:     0x55cec60d4767 - std::panicking::begin_panic_handler::{{closure}}::h6bef164c07c5cd1d
                               at /rustc/1.60.0/library/std/src/panicking.rs:588:13
  12:     0x55cec60d2754 - std::sys_common::backtrace::__rust_end_short_backtrace::ha06d828e2bf3aa2d
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55cec60d4489 - rust_begin_unwind
                               at /rustc/1.60.0/library/std/src/panicking.rs:584:5
  14:     0x55cec6047f23 - core::panicking::panic_fmt::h95a16302ac706f92
                               at /rustc/1.60.0/library/core/src/panicking.rs:143:14
  15:     0x55cec6047fb3 - core::result::unwrap_failed::h7182d5bb0014fa58
                               at /rustc/1.60.0/library/core/src/result.rs:1749:5
  16:     0x55cec605b57f - mow::main::h19257dd5480f69b5
  17:     0x55cec605ee03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h672290ab32783fa0
  18:     0x55cec6066469 - std::rt::lang_start::{{closure}}::h841e16ea26ed5a0a
  19:     0x55cec60d1a6e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he81739e93730d87f
                               at /rustc/1.60.0/library/core/src/ops/function.rs:259:13
  20:     0x55cec60d1a6e - std::panicking::try::do_call::haab80c588b564f17
                               at /rustc/1.60.0/library/std/src/panicking.rs:492:40
  21:     0x55cec60d1a6e - std::panicking::try::h44df61bdf16d5e2d
                               at /rustc/1.60.0/library/std/src/panicking.rs:456:19
  22:     0x55cec60d1a6e - std::panic::catch_unwind::h5a4755568a112d4c
                               at /rustc/1.60.0/library/std/src/panic.rs:137:14
  23:     0x55cec60d1a6e - std::rt::lang_start_internal::{{closure}}::hd1cd8cace1e688e2
                               at /rustc/1.60.0/library/std/src/rt.rs:128:48
  24:     0x55cec60d1a6e - std::panicking::try::do_call::h2a95c2966749f5f5
                               at /rustc/1.60.0/library/std/src/panicking.rs:492:40
  25:     0x55cec60d1a6e - std::panicking::try::hd43011e2f8131e56
                               at /rustc/1.60.0/library/std/src/panicking.rs:456:19
  26:     0x55cec60d1a6e - std::panic::catch_unwind::hd291d3c47494d6cf
                               at /rustc/1.60.0/library/std/src/panic.rs:137:14
  27:     0x55cec60d1a6e - std::rt::lang_start_internal::h97283ffe4f4e7a74
                               at /rustc/1.60.0/library/std/src/rt.rs:128:20
  28:     0x55cec605b922 - main
  29:     0x7fc4d8983310 - __libc_start_call_main
  30:     0x7fc4d89833c1 - __libc_start_main@GLIBC_2.2.5
  31:     0x55cec60486f5 - _start
  32:                0x0 - <unknown>
```

**Comment by korkje** [comment]
First of all, sorry about the late reply! I love your enthusiasm, I am sure we can figure this out. Pretty sure the internals are indeed close enough that only a proper id change should be sufficient in theory. Are you on Linux or macOS? There are some extra hoops to jump for Linux that I know of, so that might be the issue you are running into.

**Comment by korkje** [comment]
Maybe you are running into the same issue as discussed here https://github.com/korkje/mow/issues/1

**Comment by oemsysadm** [comment]
Hej,

No problem on the time frame, we all have lives to deal with. Your software is pretty nice and it could easily become the go-to for these mice with broader support. I'm fairly sure the O and O- is basically the same mouse except for ID, same with D and D-. Let's try and get easy support for them all?

I'm on Linux, so what else should I be looking for to try and make the code work?

**Comment by x1y** [comment]
> Hej,
> 
> No problem on the time frame, we all have lives to deal with. Your software is pretty nice and it could easily become the go-to for these mice with broader support. I'm fairly sure the O and O- is basically the same mouse except for ID, same with D and D-. Let's try and get easy support for them all?
> 
> I'm on Linux, so what else should I be looking for to try and make the code work?
> 
> Pretty sure I ran this as root, so it shouldn't be a permission issue. I'll double check some time this weekend.

Please try "sudo ./mow report battery" with the changes again, your error is consistent with what is expected without sudo or root.

**Comment by urbanslayer** [comment]
Hi,

I have also just purchased a Glorious Model D Wireless, and following this I have amended the IDs (although mine are different) - 0x2012 for wired and 0x2023 for wireless.

Installed and executed as root, so -

sudo ./mow report battery from within the release folder and it does successfully report battery usage.

report firmware (as root) displays - 

0.3.8.0

Before I try and change some settings, is there a way to output all of the rest of its config to check everything is being queried correctly?

Also, what group/permissions would we need to grant to run without root/sudo?

Thanks!

**Comment by urbanslayer** [comment]
I see, thank you and apologies!

**Comment by MrTalala** [comment]
Hello! I've recently purchased the model D wireless, and I saw a lot of posts saying it had onboard memory, and decided to get it on sale. It turns out that it does have onboard memory, but just saves everything except for debounce time. I followed the steps in this issue and all features are working with the modified ID's, except for debounce time again. I did not see this mentioned anywhere, and was wondering if any of you had the same issue. Thanks in advance!

**Comment by MrTalala** [comment]
Update: I've tried it out in a virtual machine, and after passing my mouse through to the windows vm, i was able to change my debounce time and i measured about 20 cps with short drag clicking, which is to be expected. As soon as I powered down the vm, I could no longer get anywhere near 20, and was stuck at about 9. I also decided to try mxw, a fork of mow. https://github.com/dkbednarczyk/mxw but i was unable to change my debounce time there either, but every other feature did work. Is this a model d wireless issue? Is it my system? I'm not very sure, and if y'all have any idea that would be great. Thanks again!
